### ISSUE TITLE
Discount rounding breaks normal checkout cases

### ISSUE THREAD

**Issue by unicoder88** [Ecomatic/Collector-Checkout-Magento-2#16]
Hi!

I tried updating to latest 2.0.7 but discovered a new bug - discount rounding (no_code line) adds big discount where not supposed to, even when no discounts used. Please review that code.

https://prnt.sc/lzdhd9
https://prnt.sc/lzdhic
https://prnt.sc/lzdhz1

Product price 1199, shipping 149, should be 1348, sent to Collector 1108.

Regards,
Roman

**Comment by henrik-lofstrom** [comment]
Solved in version 2.0.9
