### ISSUE TITLE
Reload cart section after shipping method change

### ISSUE THREAD

**Issue by unicoder88** [Ecomatic/Collector-Checkout-Magento-2#17]
Hi!

Do you think it's possible and makes sense to invalidate/reload 'cart' section after 'radio' change? Other AJAX handlers [have it](https://github.com/Ecomatic/Collector-Checkout-Magento-2/blob/master/Collector/Iframe/view/frontend/web/js/cart.js#L344), but this doesn't [here](https://github.com/Ecomatic/Collector-Checkout-Magento-2/blob/master/Collector/Iframe/view/frontend/web/js/cart.js#L308).

Regards,
Roman

**Comment by henrik-lofstrom** [comment]
Solved in version 2.0.9
