### ISSUE TITLE
Test mode doesn't work

### ISSUE THREAD

**Issue by YevgenK** [Ecomatic/Collector-Checkout-Magento-2#24]
Hi! 

We're trying to enable the test mode but as result we have broken checkout. 

**Steps to reproduce:**

1. Go to admin panel
2. Stores -> configuration -> collector -> checkout:  Collector Test Mode set to Yes
3. Go to frontend
4. Add a product to the cart
5. Go to checkout

**Expected result**
We should be able to create order with test credentials

**Actual result**
The checkout is broken 
![image](https://user-images.githubusercontent.com/2874309/55493941-84f52780-5642-11e9-8d28-03b99c8469a3.png)

Even if we ignore the notice message the cart is being empty. Please help us to fix it.

**Comment by davidhagg** [comment]
Could it be that you are using the store id for production?
If test mode is enabled, there are also separate StoreId's you need to enter. 
These credentials are given to you from our Merchant Services (https://merchant.collectorbank.se/integration/)

The reason to test mode and separate store ids is that the test system is totally separated from Production, and it also acts as a guard to make it harder to do calls in the wrong environment, like doing something in production when you think you are in test.

**Comment by YevgenK** [comment]
@davidhagg thank you for help! 
But now we have another problem, we can't place an order, collector server returns this response:

`{"id":"8885c034-803b-4e2d-8693-c1a5ac2e499d","sessionVersion":42,"data":null,"error":{"code":503,"message":"Service unavailable.","errors":[{"reason":"Merchant_Technical_Validation_Failed","message":"The merchant validation failed. This is due to a technical problem, e.g. timeout."}]}}`

We can't find any requests in access or error.log

**Comment by YevgenK** [comment]
It's not valid SSL certificate on our test website. The issue can be closed.
