### ISSUE TITLE
It doesnot work on magento version 2.1.x

### ISSUE THREAD

**Issue by thienphucvx** [Ecomatic/Collector-Checkout-Magento-2#8]
1 exception(s):
Exception #0 (ReflectionException): Class Magento\Framework\Serialize\SerializerInterface does not exist

Exception #0 (ReflectionException): Class Magento\Framework\Serialize\SerializerInterface does not exist
#0 /Applications/MAMP/htdocs/amberlynofinal/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#1 /Applications/MAMP/htdocs/amberlynofinal/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#2 /Applications/MAMP/htdocs/amberlynofinal/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...')
#3 /Applications/MAMP/htdocs/amberlynofinal/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#4 /Applications/MAMP/htdocs/amberlynofinal/app/code/Collector/Iframe/Block/Shipping.php(100): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#5 /Applications/MAMP/htdocs/amberlynofinal/app/code/Collector/Iframe/Block/Shipping.php(134): Collector\Iframe\Block\Shipping->getSerializer()
#6 /Applications/MAMP/htdocs/amberlynofinal/var/generation/Collector/Iframe/Block/Shipping/Interceptor.php(76): Collector\Iframe\Block\Shipping->getCountryHtmlSelect('NO', 'country_id', 'country', 'Country')
#7 /Applications/MAMP/htdocs/amberlynofinal/app/code/Collector/Iframe/view/frontend/templates/Shipping-address.phtml(107): Collector\Iframe\Block\Shipping\Interceptor->getCountryHtmlSelect()

Do you have a version which work on magento 2.1.x ?

**Comment by henrik-lofstrom** [comment]
This issue has been resolved with the latest release.
