### ISSUE TITLE
Bug on 2.1.x

### ISSUE THREAD

**Issue by thienphucvx** [Ecomatic/Collector-Checkout-Magento-2#9]
When go to checkout page : site.com/collectorcheckout/

Fatal error: Declaration of Collector\Iframe\Block\Shipping\Interceptor::isVisible() must be compatible with Collector\Iframe\Block\Shipping::isVisible(): bool in /Applications/MAMP/htdocs/amberlycollector21/var/generation/Collector/Iframe/Block/Shipping/Interceptor.php on line 7

If I remove "bool in Collector\Iframe\Block\Shipping\Interceptor::isVisible()" => it works 
But then AJAX is not working. 
CANNOT apply COUPON ( 500 internal error )
Or Update cart item quantity.

Please check image : https://ibb.co/iTzw8K

Could you test it and make sure everything works before releasing?

**Comment by henrik-lofstrom** [comment]
tested and works on Magento 2.1.3, 2.1.6, 2.1.11, 2.1.15 with module version 2.0.14
